framework  : pytorch
ccl_backend : nccl
ccl_debug   : on
use_profiler: unitrace
barrier     : on

order_of_run: [allreduce-scale, allgather-scale, reducescatter-scale  ]

implementations:
  - name: allreduce-scale
    comm_groups:
      within_node: 
        num_compute_nodes: 2
        num_gpus_per_node: 4
        gpu_ids_per_node: [0,1,2,3]
        collective:
          name: allreduce
          op: sum
          scale_up_algorithm: Tree
          scale_out_algorithm: default
          iterations: 10
          warmup_iterations: 0
          add_mxm_compute: on
          payload:
            dtype: float32
            count: 
            buffer_size: 1KB
        verify_correctness: on

  - name: allgather-scale
    comm_groups:
      across_node: 
        num_compute_nodes: 2
        num_gpus_per_node: 4
        gpu_ids_per_node: [0,1,2,3]
        collective:
          name: allgather
          op: 
          scale_up_algorithm: Collnet
          scale_out_algorithm: default
          iterations: 10
          warmup_iterations: 0
          add_mxm_compute: on
          payload:
            dtype: float32
            count: 
            buffer_size: 1KB
        verify_correctness: on

  - name: reducescatter-scale
    comm_groups:
      flatview: 
        num_compute_nodes: 2
        num_gpus_per_node: 4
        gpu_ids_per_node: [0,1,2,3]
        collective:
          name: reducescatter
          op: sum
          scale_up_algorithm: CollnetDirect
          scale_out_algorithm: default
          iterations: 10
          warmup_iterations: 0
          add_mxm_compute: on
          payload:
            dtype: float32
            count: 
            buffer_size: 1KB
        verify_correctness: on
 