framework        : pytorch
ccl_backend      : ccl
extended_logging : off
barrier          : on
device_type      : cpu
memory_source    : gpu

order_of_run: [ fsdp ,sp]

fsdp: # Task Name
  comm_group: within_node
  num_compute_nodes: 2
  num_devices_per_node: 12
  device_ids_per_node: [0,1,2,3,4,5,6,7,8,9,10,11]
  verify_correctness: on
  collective:
    collective_name: allreduce
    collective_op: sum
    scale_up_algorithm: default
    scale_out_algorithm: default
    iterations: 10
    warmup_iterations: 0
    add_mxm_compute: off
    payload:
      dtype: float32
      count: 
      buffer_size: 1KB

sp: # Task Name 
  comm_group: across_node
  num_compute_nodes: 2
  num_devices_per_node: 12
  device_ids_per_node: [0,1,2,3,4,5,6,7,8,9,10,11]
  verify_correctness: on
  collective:
    collective_name: allgather
    collective_op: sum
    scale_up_algorithm: default
    scale_out_algorithm: default
    iterations: 10
    warmup_iterations: 0
    add_mxm_compute: off
    payload:
      dtype: float32
      count: 
      buffer_size: 1KB
    

flat: # Task Name 
  comm_group: flatview
  num_compute_nodes: 2
  num_devices_per_node: 12
  device_ids_per_node: [0,1,2,3,4,5,6,7,8,9,10,11]
  verify_correctness: on
  collective:
    collective_name: allgather
    collective_op: sum
    scale_up_algorithm: default
    scale_out_algorithm: default
    iterations: 10
    warmup_iterations: 0
    add_mxm_compute: off
    payload:
      dtype: float32
      count: 
      buffer_size: 1KB